### ISSUE TITLE
Ranks Display Multiple Times

### ISSUE THREAD

**Issue by goosexinc** [meeoh/ESEA-Rank-Displayer#1]
The ranks display multiple times ultimately leading in an IP ban by ESEA for too many connections.

**Comment by meeoh** [comment]
This should of been addressed in f6c45820167e5d95981ad985a1592f0650a1c410 . Could you try getting the latest version of the chrome extension and see if that works (1.4). It works for me but someone emailed me saying its still displaying multiple ranks

https://i.imgur.com/quM0Swq.png

Otherwise, could you please send me exact recreation steps? (e.g which game you went to, did you load directly to that match or did you click into it from a different page, really any information would be helpful :))

**Comment by goosexinc** [comment]
I just added the extension and it still is showing up multiple times. I directly connect to the game from the ESEA client initially. When the game is over, I then click my alias on the ESEA client to bring up my profile on ESEA and few my recent match in which it then duplicates.

**Comment by goosexinc** [comment]
Is there any update on this as I just re-installed the extension yet again and it still does not work as the ranks continue to display multiple times ultimately leading to ESEA IP banning through Cloudflare.

**Comment by meeoh** [comment]
I’m still trying to replicate this @mynameisgoooose . I’ve installed fresh on many computers and it doesn’t happen to me. It looks like it’s only happening to people who had the old version installed then upgraded. Will keep trying and see what I can figure out. 

Could you try uninstalling and reinstalling? I feel like chrome might be caching an old version or something

I also just updated a small piece of logic that decides when to fetch, that might have an impact as well, would you be able to update try now @mynameisgoooose ?
